module.exports = {
    DEFAULT_APP_VERSION: '1.0-SNAPSHOCISKO',
    JAVA_VERSION: '17',
    LOMBOK_VERSION: '1.18.24',
    SPRING_BOOT_VERSION: '3.0.2',
    COMMONS_LANG_VERSION: '3.12.0',
    MAPSTRUCT_VERSION: '1.5.3.Final',
    LOMBOK_MAPSTRUCT_VERSION: '0.0.2',
    MAVEN_COMPILER_PLUGIN_VERSION: '3.6.2'
}
