module.exports = {
    DEFAULT_APP_VERSION: '1.0-SNAPSHOCISKO',
    JAVA_VERSION: '17',

    LOMBOK_VERSION: '1.18.30',
    SPRING_BOOT_VERSION: '3.1.5',
    MAPSTRUCT_VERSION: '1.5.5.Final',
    COMMONS_LANG3_VERSION: '3.13.0',
    LOMBOK_MAPSTRUCT_VERSION: '0.2.0',

    MAVEN_COMPILER_PLUGIN_VERSION: '3.11.0'
}
